/* oxlint-disable @stylistic/max-len */
import { join } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import { JobId, type JobOutcome } from '@deepseek-ai/dsh-jobs'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ToolDefinition, ToolRunContext } from '@deepseek-ai/dsh-tools'
import { ASSESSMENT_KINDS } from './types.ts'

declare module '@deepseek-ai/dsh-jobs' { interface JobKindMap { 'jev-audit': 'jev-audit' } }
import type { EvaluationRecord, EvaluationSummary, EvaluationSubject } from './types.ts'
function root(exec: ToolRunContext): string { const cwd = exec.agent?.session.header.cwd; if (cwd === undefined) throw new Error('devflow judgements require an owning workspace session'); return join(cwd, '.devflow') }
function actor(exec: ToolRunContext): { kind: 'agent'; session: string } { if (exec.agent === undefined) throw new Error('devflow judgement mutations require an owning agent session'); return { kind: 'agent', session: exec.agent.session.id } }
interface ToolSummary { id: string; subject: { kind: string; title: string; digest: string; cardId?: string; stage?: string; stageRevision?: number }; assessmentKind: string; status: string; decision: string; confidence: number; reasons: string[]; createdAt: string; createdCardId?: string }
function subject(value: EvaluationSubject): ToolSummary['subject'] { return value.kind === 'request' ? { kind: value.kind, title: value.title, digest: value.digest } : { kind: value.kind, title: value.title, digest: value.digest, cardId: value.cardId, stage: value.stage, stageRevision: value.stageRevision } }
function summary(value: EvaluationSummary | EvaluationRecord): ToolSummary { return { id: value.id, subject: subject(value.subject), assessmentKind: value.assessmentKind, status: value.status, decision: value.decision, confidence: value.confidence, reasons: [...value.reasons], createdAt: value.createdAt, ...(value.createdCardId === undefined ? {} : { createdCardId: value.createdCardId }) } }
const SUBJECT = { type: 'object', required: true, additionalProperties: false, properties: { kind: { type: 'string', required: true }, title: { type: 'string', required: true }, digest: { type: 'string', required: true }, cardId: { type: 'string' }, stage: { type: 'string' }, stageRevision: { type: 'integer' } } } as const
const SUMMARY = { type: 'object', additionalProperties: false, properties: { id: { type: 'string', required: true }, subject: SUBJECT, assessmentKind: { type: 'string', required: true }, status: { type: 'string', required: true }, decision: { type: 'string', required: true }, confidence: { type: 'number', required: true }, reasons: { type: 'array', required: true, items: { type: 'string' } }, createdAt: { type: 'string', required: true }, createdCardId: { type: 'string' } } } as const
function line(value: ToolSummary): string { const target = value.subject.cardId ?? value.subject.title; return `${value.id} [${value.status}/${value.decision}] ${value.assessmentKind} ${target} (${Math.round(value.confidence * 100)}%)${value.createdCardId === undefined ? '' : ` -> ${value.createdCardId}`}` }
export function registerTools(ctx: Context): void {
  const register = (definition: ToolDefinition): void => { ctx.effect(() => ctx.tools.register(definition)) }
  register(defineTool({ name: 'devflow_assess_request', description: 'Evaluate proposed repository work before creating a Devflow card. The durable result may become an explicit proposal; this tool never creates a card itself.', parameters: { title: { type: 'string', required: true }, body: { type: 'string', required: true }, assessmentKind: { type: 'string', enum: [...ASSESSMENT_KINDS], description: 'Omit for intake.' } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.assessRequest({ root: root(exec), title: args.title, body: args.body, ...(args.assessmentKind === undefined ? {} : { assessmentKind: args.assessmentKind }) }, exec.signal)), presentCall: args => ({ card: 'generic', kind: 'read', title: `Assess Devflow request: ${args.title}` }) }))
  register(defineTool({ name: 'devflow_assess', description: 'Run a durable typed judgement over an existing Devflow card at its current stage revision. It records advice and never changes the card stage.', parameters: { id: { type: 'string', required: true }, assessmentKind: { type: 'string', required: true, enum: [...ASSESSMENT_KINDS] } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.assessCard({ root: root(exec), cardId: args.id, assessmentKind: args.assessmentKind }, exec.signal)), presentCall: args => ({ card: 'generic', kind: 'read', title: `Assess ${args.id}: ${args.assessmentKind}` }) }))
  register(defineTool({ name: 'devflow_judgements', description: 'List this project\'s durable JEV evaluations. Pass an id to return that evaluation as a one-row list.', parameters: { id: { type: 'string' } }, output: { schema: { type: 'array', items: SUMMARY }, render: (_args, value) => [{ type: 'text', text: value.map(line).join('\n') || 'No Devflow judgements.' }] }, execute: async (args, exec) => args.id === undefined ? (await ctx.devflowJev.list(root(exec))).map(summary) : [summary(await ctx.devflowJev.read(root(exec), args.id))], presentCall: args => ({ card: 'generic', kind: 'read', title: args.id === undefined ? 'List Devflow judgements' : `Read judgement ${args.id}` }) }))
  register(defineTool({ name: 'devflow_accept_judgement', description: 'Accept an actionable request assessment and idempotently create its proposed Devflow card. Repeating the call returns the same created card.', parameters: { id: { type: 'string', required: true } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.accept(root(exec), args.id, actor(exec))), presentCall: args => ({ card: 'generic', kind: 'edit', title: `Accept judgement ${args.id}` }) }))
  register(defineTool({ name: 'devflow_reject_judgement', description: 'Reject a pending Devflow judgement proposal. The evaluation remains available for audit.', parameters: { id: { type: 'string', required: true } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => { actor(exec); return summary(await ctx.devflowJev.reject(root(exec), args.id)) }, presentCall: args => ({ card: 'generic', kind: 'edit', title: `Reject judgement ${args.id}` }) }))

  const AUDIT_OUTPUT = { schema: { type: 'object', additionalProperties: false, properties: { text: { type: 'string', required: true } } }, render: (_args: unknown, value: { text: string }) => [{ type: 'text' as const, text: value.text }] } as const
  const start = async (exec: ToolRunContext, auditRoot: string, runId: string, resume: boolean): Promise<string> => {
    const jobs = ctx.get('jobs'); if (jobs === undefined || exec.agent === undefined) throw new Error('JOBS_UNAVAILABLE: project audits need a live owner and jobs controller')
    const id = jobs.start({ kind: 'jev-audit', owner: exec.agent, label: `JEV project audit ${runId}`,
      run: () => { const controller = new AbortController(); let output = ''
        const progress = (message: string) => { output = (output + message + '\n').slice(-65536) }
        const operation = resume ? ctx.devflowJev.resumeAudit(auditRoot, runId, controller.signal, progress) : ctx.devflowJev.runAudit(auditRoot, runId, controller.signal, progress)
        const done: Promise<JobOutcome> = operation.then(result => ({ status: controller.signal.aborted ? 'killed' as const : 'completed' as const, output: JSON.stringify(result) }), (error: unknown) => ({ status: controller.signal.aborted ? 'killed' as const : 'failed' as const, output: error instanceof Error ? error.message : String(error) }))
        return { cancel: () => { controller.abort() }, done, readOutput: () => { const value = output; output = ''; return value } }
      },
    })
    await ctx.devflowJev.bindAuditJob(auditRoot, runId, id); return id
  }
  register(defineTool({ name: 'devflow_audit_project', description: 'Start a durable, read-only, stage-aware JEV audit of the current project. It never creates or moves cards.', parameters: { profile: { type: 'string', enum: ['delivery-health', 'release', 'risk', 'spec', 'full'], description: 'Defaults to delivery-health.' }, maxCards: { type: 'number', description: 'Maximum active cards to snapshot, 1-200.' } }, output: AUDIT_OUTPUT,
    execute: async (args, exec) => { const auditRoot = root(exec); const prepared = await ctx.devflowJev.prepareAudit({ root: auditRoot, ...(args.profile === undefined ? {} : { profile: args.profile }), ...(args.maxCards === undefined ? {} : { maxCards: args.maxCards }) }); const jobId = await start(exec, auditRoot, prepared.manifest.id, false); return { text: JSON.stringify({ ...prepared, jobId }) } }, presentCall: () => ({ card: 'generic', kind: 'read', title: 'Audit current Devflow project' }) }))
  register(defineTool({ name: 'devflow_audits', description: 'List durable project audits or inspect one run.', parameters: { runId: { type: 'string' } }, output: AUDIT_OUTPUT, execute: async (args, exec) => ({ text: JSON.stringify(args.runId === undefined ? await ctx.devflowJev.listAudits(root(exec)) : await ctx.devflowJev.inspectAudit(root(exec), args.runId)) }), presentCall: args => ({ card: 'generic', kind: 'read', title: args.runId === undefined ? 'List project audits' : `Inspect audit ${args.runId}` }) }))
  register(defineTool({ name: 'devflow_resume_audit', description: 'Resume unfinished checks in an interrupted, cancelled, or partially failed project audit.', parameters: { runId: { type: 'string', required: true } }, output: AUDIT_OUTPUT, execute: async (args, exec) => ({ text: JSON.stringify({ runId: args.runId, jobId: await start(exec, root(exec), args.runId, true) }) }), presentCall: args => ({ card: 'generic', kind: 'edit', title: `Resume audit ${args.runId}` }) }))
  register(defineTool({ name: 'devflow_cancel_audit', description: 'Request cancellation of the Harness job running a project audit.', parameters: { runId: { type: 'string', required: true } }, output: AUDIT_OUTPUT, execute: async (args, exec) => { const jobs = ctx.get('jobs'); if (jobs === undefined || exec.agent === undefined) throw new Error('JOBS_UNAVAILABLE'); const audit = await ctx.devflowJev.inspectAudit(root(exec), args.runId); if (audit.state.jobId === undefined) throw new Error(`devflow-jev: audit ${args.runId} has no job`); return { text: JSON.stringify({ runId: args.runId, outcome: jobs.kill(JobId(audit.state.jobId), exec.agent, 'project audit cancelled') }) } }, presentCall: args => ({ card: 'generic', kind: 'edit', title: `Cancel audit ${args.runId}` }) }))
}
