/* oxlint-disable @stylistic/max-len */
import { join } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ToolDefinition, ToolRunContext } from '@deepseek-ai/dsh-tools'
import { ASSESSMENT_KINDS } from './types.ts'

import type { EvaluationRecord, EvaluationSummary, EvaluationSubject } from './types.ts'
function root(exec: ToolRunContext): string { const cwd = exec.agent?.session.header.cwd; if (cwd === undefined) throw new Error('devflow judgements require an owning workspace session'); return join(cwd, '.devflow') }
function actor(exec: ToolRunContext): { kind: 'agent'; session: string } { if (exec.agent === undefined) throw new Error('devflow judgement mutations require an owning agent session'); return { kind: 'agent', session: exec.agent.session.id } }
interface ToolSummary { id: string; subject: { kind: string; title: string; digest: string; cardId?: string; stage?: string; stageRevision?: number }; assessmentKind: string; status: string; decision: string; confidence: number; reasons: string[]; createdAt: string; createdCardId?: string }
function subject(value: EvaluationSubject): ToolSummary['subject'] { return value.kind === 'request' ? { kind: value.kind, title: value.title, digest: value.digest } : { kind: value.kind, title: value.title, digest: value.digest, cardId: value.cardId, stage: value.stage, stageRevision: value.stageRevision } }
function summary(value: EvaluationSummary | EvaluationRecord): ToolSummary { return { id: value.id, subject: subject(value.subject), assessmentKind: value.assessmentKind, status: value.status, decision: value.decision, confidence: value.confidence, reasons: [...value.reasons], createdAt: value.createdAt, ...(value.createdCardId === undefined ? {} : { createdCardId: value.createdCardId }) } }
const SUBJECT = { type: 'object', required: true, additionalProperties: false, properties: { kind: { type: 'string', required: true }, title: { type: 'string', required: true }, digest: { type: 'string', required: true }, cardId: { type: 'string' }, stage: { type: 'string' }, stageRevision: { type: 'integer' } } } as const
const SUMMARY = { type: 'object', additionalProperties: false, properties: { id: { type: 'string', required: true }, subject: SUBJECT, assessmentKind: { type: 'string', required: true }, status: { type: 'string', required: true }, decision: { type: 'string', required: true }, confidence: { type: 'number', required: true }, reasons: { type: 'array', required: true, items: { type: 'string' } }, createdAt: { type: 'string', required: true }, createdCardId: { type: 'string' } } } as const
function line(value: ToolSummary): string { const target = value.subject.cardId ?? value.subject.title; return `${value.id} [${value.status}/${value.decision}] ${value.assessmentKind} ${target} (${Math.round(value.confidence * 100)}%)${value.createdCardId === undefined ? '' : ` -> ${value.createdCardId}`}` }
export function registerTools(ctx: Context): void {
  const register = (definition: ToolDefinition): void => { ctx.effect(() => ctx.tools.register(definition)) }
  register(defineTool({ name: 'devflow_assess', description: 'Evaluate a proposed request or an existing Devflow card. Request requires title/body; card requires id/assessmentKind. Persists advice without creating or moving cards. Query results with jev_list source devflow-assessment.', parameters: { target: { type: 'string', required: true, enum: ['request', 'card'] }, title: { type: 'string' }, body: { type: 'string' }, id: { type: 'string' }, assessmentKind: { type: 'string', enum: [...ASSESSMENT_KINDS] } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.assess(root(exec), args, exec.signal)), presentCall: args => ({ card: 'generic', kind: 'read', title: `Assess Devflow ${args.target}: ${args.title ?? args.id ?? ''}` }) }))
  register(defineTool({ name: 'devflow_decide_judgement', description: 'Accept or reject a pending request judgement. Accept idempotently creates its proposed Devflow card; reject keeps the evaluation for audit.', parameters: { id: { type: 'string', required: true }, action: { type: 'string', required: true, enum: ['accept', 'reject'] } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.decideJudgement(root(exec), args.id, args.action, actor(exec))), presentCall: args => ({ card: 'generic', kind: 'edit', title: `${args.action} judgement ${args.id}` }) }))
}
