/* oxlint-disable @stylistic/max-len */
import { join } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ToolRunContext } from '@deepseek-ai/dsh-tools'
import { ASSESSMENT_KINDS } from './types.ts'
import type { EvaluationRecord, EvaluationSummary, EvaluationSubject } from './types.ts'
function root(exec: ToolRunContext): string { const cwd = exec.agent?.session.header.cwd; if (cwd === undefined) throw new Error('devflow judgements require an owning workspace session'); return join(cwd, '.devflow') }
function actor(exec: ToolRunContext): { kind: 'agent'; session: string } { if (exec.agent === undefined) throw new Error('devflow judgement mutations require an owning agent session'); return { kind: 'agent', session: exec.agent.session.id } }
interface ToolSummary { id: string; subject: { kind: string; title: string; digest: string; cardId?: string; stage?: string; stageRevision?: number }; assessmentKind: string; status: string; decision: string; confidence: number; reasons: string[]; createdAt: string; createdCardId?: string }
function subject(value: EvaluationSubject): ToolSummary['subject'] { return value.kind === 'request' ? { kind: value.kind, title: value.title, digest: value.digest } : { kind: value.kind, title: value.title, digest: value.digest, cardId: value.cardId, stage: value.stage, stageRevision: value.stageRevision } }
function summary(value: EvaluationSummary | EvaluationRecord): ToolSummary { return { id: value.id, subject: subject(value.subject), assessmentKind: value.assessmentKind, status: value.status, decision: value.decision, confidence: value.confidence, reasons: [...value.reasons], createdAt: value.createdAt, ...(value.createdCardId === undefined ? {} : { createdCardId: value.createdCardId }) } }
const SUBJECT = { type: 'object', required: true, additionalProperties: false, properties: { kind: { type: 'string', required: true }, title: { type: 'string', required: true }, digest: { type: 'string', required: true }, cardId: { type: 'string' }, stage: { type: 'string' }, stageRevision: { type: 'integer' } } } as const
const SUMMARY = { type: 'object', additionalProperties: false, properties: { id: { type: 'string', required: true }, subject: SUBJECT, assessmentKind: { type: 'string', required: true }, status: { type: 'string', required: true }, decision: { type: 'string', required: true }, confidence: { type: 'number', required: true }, reasons: { type: 'array', required: true, items: { type: 'string' } }, createdAt: { type: 'string', required: true }, createdCardId: { type: 'string' } } } as const
function line(value: ToolSummary): string { const target = value.subject.cardId ?? value.subject.title; return `${value.id} [${value.status}/${value.decision}] ${value.assessmentKind} ${target} (${Math.round(value.confidence * 100)}%)${value.createdCardId === undefined ? '' : ` -> ${value.createdCardId}`}` }
export function registerTools(ctx: Context): void {
  ctx.tools.register(defineTool({ name: 'devflow_assess_request', description: 'Evaluate proposed repository work before creating a Devflow card. The durable result may become an explicit proposal; this tool never creates a card itself.', parameters: { title: { type: 'string', required: true }, body: { type: 'string', required: true }, assessmentKind: { type: 'string', enum: [...ASSESSMENT_KINDS], description: 'Omit for intake.' } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.assessRequest({ root: root(exec), title: args.title, body: args.body, ...(args.assessmentKind === undefined ? {} : { assessmentKind: args.assessmentKind }) }, exec.signal)), presentCall: args => ({ card: 'generic', kind: 'read', title: `Assess Devflow request: ${args.title}` }) }))
  ctx.tools.register(defineTool({ name: 'devflow_assess', description: 'Run a durable typed judgement over an existing Devflow card at its current stage revision. It records advice and never changes the card stage.', parameters: { id: { type: 'string', required: true }, assessmentKind: { type: 'string', required: true, enum: [...ASSESSMENT_KINDS] } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.assessCard({ root: root(exec), cardId: args.id, assessmentKind: args.assessmentKind }, exec.signal)), presentCall: args => ({ card: 'generic', kind: 'read', title: `Assess ${args.id}: ${args.assessmentKind}` }) }))
  ctx.tools.register(defineTool({ name: 'devflow_judgements', description: 'List this project\'s durable JEV evaluations. Pass an id to return that evaluation as a one-row list.', parameters: { id: { type: 'string' } }, output: { schema: { type: 'array', items: SUMMARY }, render: (_args, value) => [{ type: 'text', text: value.map(line).join('\n') || 'No Devflow judgements.' }] }, execute: async (args, exec) => args.id === undefined ? (await ctx.devflowJev.list(root(exec))).map(summary) : [summary(await ctx.devflowJev.read(root(exec), args.id))], presentCall: args => ({ card: 'generic', kind: 'read', title: args.id === undefined ? 'List Devflow judgements' : `Read judgement ${args.id}` }) }))
  ctx.tools.register(defineTool({ name: 'devflow_accept_judgement', description: 'Accept an actionable request assessment and idempotently create its proposed Devflow card. Repeating the call returns the same created card.', parameters: { id: { type: 'string', required: true } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => summary(await ctx.devflowJev.accept(root(exec), args.id, actor(exec))), presentCall: args => ({ card: 'generic', kind: 'edit', title: `Accept judgement ${args.id}` }) }))
  ctx.tools.register(defineTool({ name: 'devflow_reject_judgement', description: 'Reject a pending Devflow judgement proposal. The evaluation remains available for audit.', parameters: { id: { type: 'string', required: true } }, output: { schema: SUMMARY, render: (_args, value) => [{ type: 'text', text: line(value) }] }, execute: async (args, exec) => { actor(exec); return summary(await ctx.devflowJev.reject(root(exec), args.id)) }, presentCall: args => ({ card: 'generic', kind: 'edit', title: `Reject judgement ${args.id}` }) }))
}
