/* oxlint-disable @stylistic/max-len */
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import type { AuditProfile, AuditSummary, EvaluationRecord, EvaluationSummary } from '../types.ts'
import { request } from './api.ts'
import type { Translate } from './locales.ts'
import css from './panel.module.css'
export interface Props { sessionId: string; visible: boolean; refreshMs: number; t: Translate }
export function JudgementPanel(props: Props) { return props.sessionId.trim() === '' ? <p>{props.t('noProject')}</p> : <ProjectPanel key={props.sessionId} {...props} /> }
function ProjectPanel(props: Props) { const [view, setView] = useState<'audits' | 'judgements'>('audits'); return <section className={css.page}><nav className={css.tabs}><button className={view === 'audits' ? css.active : ''} onClick={() => { setView('audits') }}>{props.t('audits')}</button><button className={view === 'judgements' ? css.active : ''} onClick={() => { setView('judgements') }}>{props.t('judgements')}</button></nav>{view === 'audits' ? <AuditPanel {...props} /> : <IndividualPanel {...props} />}</section> }
function IndividualPanel({ sessionId, visible, refreshMs, t }: Props) {
  const [items, setItems] = useState<EvaluationSummary[]>(); const [selected, setSelected] = useState<EvaluationRecord>(); const [form, setForm] = useState(false)
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const alive = useRef(true); const reading = useRef<AbortController>()
  const refresh = useCallback(async () => { if (reading.current !== undefined) return; const controller = new AbortController(); reading.current = controller
    try { const next = await request({ method: 'list', sessionId }, controller.signal); if (!controller.signal.aborted && alive.current) { setItems(next); setError('') } }
    catch (failure) { if (!controller.signal.aborted && alive.current) setError(String(failure)) } finally { if (reading.current === controller) reading.current = undefined }
  }, [sessionId])
  useEffect(() => () => { alive.current = false; reading.current?.abort() }, [])
  useEffect(() => { if (!visible) return; const run = () => { if (document.visibilityState !== 'hidden') void refresh() }; run(); const timer = window.setInterval(run, refreshMs); document.addEventListener('visibilitychange', run); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', run); reading.current?.abort(); reading.current = undefined } }, [visible, refreshMs, refresh])
  const open = async (id: string) => { setBusy(true); setError(''); try { setSelected(await request({ method: 'read', sessionId, id })) } catch (failure) { setError(String(failure)) } finally { setBusy(false) } }
  const action = async (method: 'accept' | 'reject') => { if (selected === undefined) return; setBusy(true); setError(''); try { setSelected(await request({ method, sessionId, id: selected.id })); setNotice(t('saved')); await refresh() } catch (failure) { setError(String(failure)) } finally { setBusy(false) } }
  const assess = async (title: string, body: string) => { setBusy(true); setError(''); try { const record = await request({ method: 'assess', sessionId, title, body }); setForm(false); setSelected(record); setNotice(t('saved')); await refresh() } catch (failure) { setError(String(failure)) } finally { setBusy(false) } }
  return <div className={css.inner} aria-label={t('title')}><header className={css.header}><h2>{t('judgements')}</h2><div className={css.actions}><button onClick={() => { setForm(true) }}>{t('newAssessment')}</button><button onClick={() => void refresh()}>{t('refresh')}</button></div></header><div className={css.body}>
    {error !== '' && <div role="alert" className={css.error}>{items !== undefined && <p>{t('stale')}</p>}{error}</div>}{notice !== '' && <p role="status" className={css.notice}>{notice}</p>}
    {form && <AssessmentForm busy={busy} t={t} close={() => { setForm(false) }} submit={assess} />}
    {selected !== undefined ? <Detail value={selected} busy={busy} t={t} back={() => { setSelected(undefined) }} accept={() => void action('accept')} reject={() => void action('reject')} /> : items === undefined ? <p>{t('loading')}</p> : items.length === 0 ? <p>{t('empty')}</p> : items.map(item => <button className={css.card} key={item.id} onClick={() => void open(item.id)}><div className={css.row}><h3>{item.subject.title}</h3><span className={css.badge}>{item.status} · {item.decision}</span></div><p className={css.note}>{item.assessmentKind} · {Math.round(item.confidence * 100)}% · {new Date(item.createdAt).toLocaleString()}</p></button>)}
  </div></div>
}
function AuditPanel({ sessionId, visible, refreshMs, t }: Props) {
  const [items, setItems] = useState<AuditSummary[]>(); const [selected, setSelected] = useState<AuditSummary>(); const [profile, setProfile] = useState<AuditProfile>('delivery-health'); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const selectedRef = useRef<AuditSummary>(); useEffect(() => { selectedRef.current = selected }, [selected])
  const refresh = useCallback(async () => { try { const next = await request({ method: 'audit-list', sessionId }); setItems(next); const current = selectedRef.current; if (current !== undefined) setSelected(next.find(item => item.manifest.id === current.manifest.id) ?? current); setError('') } catch (failure) { setError(String(failure)) } }, [sessionId])
  useEffect(() => { if (!visible) return; void refresh(); const timer = window.setInterval(() => { if (document.visibilityState !== 'hidden') void refresh() }, refreshMs); return () => { window.clearInterval(timer) } }, [visible, refreshMs, refresh])
  const start = async () => { setBusy(true); setError(''); try { const result = await request({ method: 'audit-start', sessionId, profile, maxCards: 50 }); if (result.manifest !== undefined && result.state !== undefined) setSelected({ manifest: result.manifest, state: result.state }); await refresh() } catch (failure) { setError(String(failure)) } finally { setBusy(false) } }
  const action = async (method: 'audit-cancel' | 'audit-resume') => { if (selected === undefined) return; setBusy(true); setError(''); try { await request({ method, sessionId, runId: selected.manifest.id }); await refresh() } catch (failure) { setError(String(failure)) } finally { setBusy(false) } }
  if (selected !== undefined) return <div className={css.inner}><header className={css.header}><button onClick={() => { setSelected(undefined) }}>{t('back')}</button><button onClick={() => void refresh()}>{t('refresh')}</button></header><div className={css.body}>{error !== '' && <p className={css.error}>{error}</p>}<article className={`${css.card} ${css.detail}`}><div className={css.row}><h3>{selected.manifest.profile}</h3><span className={css.badge}>{selected.state.status}</span></div><p>{t('progress')}: {selected.state.completed}/{selected.state.total} · {t('errors')} {selected.state.failed}</p><p>{selected.state.conclusion ?? ''}</p><h3>{t('findings')}</h3>{selected.state.findings.length === 0 ? <p>—</p> : <ul>{selected.state.findings.map((finding, index) => <li key={`${finding.code}-${index}`}>[{finding.severity}] {finding.cardId === undefined ? '' : `${finding.cardId}: `}{finding.message}</li>)}</ul>}<h3>{t('checks')}</h3>{selected.state.results.length === 0 ? <p>—</p> : <ul>{selected.state.results.map(result => <li key={result.check.id}><strong>{result.check.cardTitle}</strong> ({result.check.cardId}) · {result.check.assessmentKind} · {result.status}{result.evaluationId === undefined ? '' : ` · ${result.evaluationId}`}{result.error === undefined ? '' : <span className={css.error}> · {result.error}</span>}</li>)}</ul>}<div className={css.actions}>{selected.state.status === 'running' && <button disabled={busy} onClick={() => void action('audit-cancel')}>{t('cancelAudit')}</button>}{['interrupted', 'cancelled', 'completed-with-errors'].includes(selected.state.status) && <button disabled={busy} onClick={() => void action('audit-resume')}>{t('resumeAudit')}</button>}</div></article></div></div>
  return <div className={css.inner}><header className={css.header}><h2>{t('audits')}</h2><button onClick={() => void refresh()}>{t('refresh')}</button></header><div className={css.body}>{error !== '' && <p className={css.error}>{error}</p>}<div className={css.form}><label>{t('profile')}<select value={profile} onChange={(event) => { setProfile(event.target.value as AuditProfile) }}><option value="delivery-health">delivery-health</option><option value="release">release</option><option value="risk">risk</option><option value="spec">spec</option><option value="full">full</option></select></label><button disabled={busy} onClick={() => void start()}>{t('startAudit')}</button></div>{items === undefined ? <p>{t('loading')}</p> : items.length === 0 ? <p>{t('noAudits')}</p> : items.map(item => <button className={css.card} key={item.manifest.id} onClick={() => { setSelected(item) }}><div className={css.row}><h3>{item.manifest.profile}</h3><span className={css.badge}>{item.state.status}</span></div><p className={css.note}>{item.state.completed}/{item.state.total} · {new Date(item.manifest.createdAt).toLocaleString()}</p></button>)}</div></div>
}
function AssessmentForm({ busy, t, close, submit }: { busy: boolean; t: Translate; close: () => void; submit: (title: string, body: string) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [body, setBody] = useState('')
  const send = (event: FormEvent) => { event.preventDefault(); void submit(title, body) }
  return <form className={css.form} onSubmit={send}><label>{t('titleField')}<input required value={title} onChange={(event) => { setTitle(event.target.value) }} /></label><label>{t('body')}<textarea required value={body} onChange={(event) => { setBody(event.target.value) }} /></label><div className={css.actions}><button disabled={busy}>{t('assess')}</button><button type="button" onClick={close}>{t('close')}</button></div></form>
}
function Detail({ value, busy, t, back, accept, reject }: { value: EvaluationRecord; busy: boolean; t: Translate; back: () => void; accept: () => void; reject: () => void }) {
  return <article className={`${css.card} ${css.detail}`}><button onClick={back}>{t('back')}</button><div className={css.row}><h3>{value.subject.title}</h3><span className={css.badge}>{value.status} · {value.decision}</span></div><p>{t('confidence')}: {Math.round(value.confidence * 100)}%</p><h3>{t('reasons')}</h3><ul>{value.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>{value.missingInformation.length > 0 && <><h3>{t('missing')}</h3><ul>{value.missingInformation.map(reason => <li key={reason}>{reason}</li>)}</ul></>}{value.error !== undefined && <p className={css.error}>{t('unavailable')}: [{value.error.code}] {value.error.message}</p>}{value.createdCardId !== undefined && <p>{t('createdCard')}: {value.createdCardId}</p>}<details><summary>{t('answers')}</summary><pre>{JSON.stringify(value.answers, null, 2)}</pre></details>{value.status === 'review' && value.decision === 'propose' && <div className={css.actions}><button disabled={busy} onClick={accept}>{t('accept')}</button><button disabled={busy} onClick={reject}>{t('reject')}</button></div>}</article>
}
