const STAGES=[['draft','需求草稿','#98a7b9'],['designing','方案设计','#8f80c6'],['ready','待开发','#6b9dc7'],['developing','开发中','#4d96c8'],['reviewing','评审','#d5a463'],['testing','验证','#68ad9b'],['done','已完成','#7dab83']]
const board=document.querySelector('#board'),summary=document.querySelector('#summary'),updated=document.querySelector('#updated'),error=document.querySelector('#error'),shade=document.querySelector('#shade'),detail=document.querySelector('#detail'),detailContent=document.querySelector('#detail-content')
const search=document.querySelector('#search'),blockedOnly=document.querySelector('#blocked-only')
let cards=[];let selected=null
function node(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element}
function render(){const query=search.value.trim().toLocaleLowerCase();const visible=cards.filter(card=>(!blockedOnly.checked||card.stage==='blocked')&&(!query||`${card.id} ${card.title}`.toLocaleLowerCase().includes(query)));board.replaceChildren();for(const [stage,label,color] of STAGES){const items=visible.filter(card=>(card.stage==='blocked'?card.blockedFrom:card.stage)===stage);const column=node('section','column');column.style.setProperty('--accent',color);const head=node('div','column-head'),name=node('div','column-name');name.append(node('span','dot'),node('span','',label));head.append(name,node('span','count',String(items.length)));column.append(head);const list=node('div','cards');if(!items.length)list.append(node('div','empty','暂无卡片'));for(const card of items){const button=node('button','card');button.type='button';button.append(node('span','id',card.id),node('strong','',card.title));const bottom=node('div','bottom');bottom.append(node('span','',card.parent?`子任务 · ${card.parent}`:`Rev ${card.stageRevision}`));if(card.stage==='blocked')bottom.append(node('span','badge blocked','受阻'));else if(card.serviceClass!=='standard')bottom.append(node('span','badge',card.serviceClass));button.append(bottom);button.addEventListener('click',()=>openCard(card.id));list.append(button)}column.append(list);board.append(column)}}
async function get(path){const response=await fetch(path,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result}
async function refresh(){try{const data=await get('/api/cards');cards=data.cards;document.title=`Devflow · ${data.projectRoot||'项目看板'}`;summary.textContent=`${data.projectRoot||'当前项目'} · ${cards.length} 张活跃卡片 · ${cards.filter(card=>card.stage==='blocked').length} 张受阻`;updated.textContent=`更新于 ${new Date(data.updatedAt).toLocaleTimeString('zh-CN')}`;error.hidden=true;render();if(selected)await loadCard(selected)}catch(cause){error.textContent=`读取失败：${cause.message}`;error.hidden=false;updated.textContent='连接失败'}}
function line(grid,key,value){grid.append(node('dt','',key),node('dd','',value??'—'))}
async function loadCard(id){const card=await get(`/api/cards/${encodeURIComponent(id)}`);const body=node('div','detail-body');body.append(node('span','id',card.id),node('h2','',card.title));const grid=node('dl','meta');line(grid,'阶段',card.stage==='blocked'?`受阻 · 来自 ${card.blockedFrom}`:STAGES.find(([stage])=>stage===card.stage)?.[1]);line(grid,'修订',String(card.stageRevision));line(grid,'服务类别',card.serviceClass);line(grid,'父卡片',card.parent);line(grid,'更新时间',new Date(card.updatedAt).toLocaleString('zh-CN'));body.append(grid,node('h3','','需求正文'),node('pre','body-text',card.body||'暂无正文'),node('h3','',`已登记产物 · ${card.artifacts.length}`));if(!card.artifacts.length)body.append(node('p','empty','暂无产物'));for(const record of card.artifacts){const item=node('div','artifact',record.kind||'文件产物');item.append(node('small','',`${record.path} · Rev ${record.rev}`));body.append(item)}detailContent.replaceChildren(body)}
async function openCard(id){selected=id;shade.hidden=false;detail.classList.add('open');detail.setAttribute('aria-hidden','false');detailContent.replaceChildren(node('p','detail-body','读取中…'));try{await loadCard(id)}catch(cause){detailContent.replaceChildren(node('p','detail-body',`读取失败：${cause.message}`))}}
function closeCard(){selected=null;shade.hidden=true;detail.classList.remove('open');detail.setAttribute('aria-hidden','true')}
document.querySelector('#refresh').addEventListener('click',refresh);document.querySelector('#close').addEventListener('click',closeCard);shade.addEventListener('click',closeCard);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeCard()});search.addEventListener('input',render);blockedOnly.addEventListener('change',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});setInterval(()=>{if(!document.hidden)refresh()},5000);refresh()
